version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.24.1
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: npm ci
    - run: npm test
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - persist_to_workspace:
        root: ~/repo
        paths: ['.']

  release:
    docker:
    - image: circleci/node:10.24.1
    working_directory: ~/repo
    steps:
    - attach_workspace:
        at: ~/repo
    - run: npx semantic-release

workflows:
  version: 2
  build_and_release:
    jobs:
    - build:
        filters:
          tags:
            ignore: /^\d+\.\d+\.\d+/
    - release:
        requires:
          - build
        filters:
          branches:
            only: master
